[project]
name = 'PollinatorChain-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.habitat-corridor-registry]
path = 'contracts/habitat-corridor-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.pesticide-exposure-monitoring]
path = 'contracts/pesticide-exposure-monitoring.clar'
clarity_version = 3
epoch = '3.2'

[contracts.pollinator-flight-tracking]
path = 'contracts/pollinator-flight-tracking.clar'
clarity_version = 3
epoch = '3.2'

[contracts.pollinator-support-rewards]
path = 'contracts/pollinator-support-rewards.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
